language: node_js

cache:
  directories:
    - 'node_modules'

services:
  - mongodb

before_script:
  - sleep 15

script:
  - yarn test
  - yarn test:integration
  - yarn build-client
  - build-storybook
  - yarn docs
  - deploy-storybook
